name: Tests Linux

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  LANG: en_US.UTF-8
  LS_ALL: en_US.UTF-8
  LANGUAGE: en_US:en  

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run:  |
        echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections
        sudo apt-get -y update
        sudo apt-get -y install locales
        sudo sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen
        sudo apt-get -y install software-properties-common
        sudo add-apt-repository -y ppa:flacon
        sudo apt-get -y update
        sudo apt-get -y install build-essential pkg-config cmake  qtbase5-dev qttools5-dev-tools qttools5-dev libuchardet-dev libtag1-dev
        sudo apt-get -y install flac mac alacenc vorbis-tools wavpack lame ttaenc faac opus-tools sox

    - name: Clone tools
      run: git clone https://github.com/SokoloffA/nightly-tools.git ~/tools

    - name: Create Build Environment
      run: |
        cmake -E make_directory ${{github.workspace}}/build
        cmake -E make_directory ${HOME}/app

    - name: Run CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake -DCMAKE_INSTALL_PREFIX=${HOME}/app/usr -DAPPIMAGE_BUNDLE=Yes -DCMAKE_BUILD_TYPE=$BUILD_TYPE $GITHUB_WORKSPACE

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: make -j 8

    - name: Install
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: make install


    - name: Build AppImage
      working-directory: ${HOME}/app
      shell: bash
      run: ls
